version: '2'
services:
  mkdocs:
    image: squidfunk/mkdocs-material:4.6.0
    container_name: mkdocs
    ports:
      - "8000:8000"
    volumes:
      - ./:/docs
    # command: sh pip install mkdocs-markdownextradata-plugin
    # command: echo "test"
    tty: true
    entrypoint: /bin/sh /docs/entrypoint.sh